const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const fs   = require('fs');
const path = require('path');
const db   = require('../config/db');

const REPORTS_DIR = path.join(__dirname, '../generated_reports');
if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

function createTransporter() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT) || 587,
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

async function generateWeeklyPDF(reports, weekStart, weekEnd) {
  return new Promise((resolve, reject) => {
    const fileName = `TARIPA_PTRO_Report_${weekStart}_to_${weekEnd}.pdf`;
    const filePath = path.join(REPORTS_DIR, fileName);
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // ── Header ──────────────────────────────────────────────
    doc.fontSize(18).font('Helvetica-Bold').text('TARIPA SYSTEM', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Tricycle Fare Monitoring & Accountability System', { align: 'center' });
    doc.text('Angeles City, Pampanga', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).font('Helvetica-Bold')
       .text(`Weekly Overcharging Report`, { align: 'center' });
    doc.fontSize(10).font('Helvetica')
       .text(`Reporting Period: ${weekStart} to ${weekEnd}`, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleString('en-PH')}`, { align: 'center' });
    doc.text(`Submitted to: Angeles City Public Transport Regulatory Office (PTRO)`, { align: 'center' });

    doc.moveDown(2);
    doc.fontSize(12).font('Helvetica-Bold').text(`Total Reports This Week: ${reports.length}`);
    doc.moveDown();

    // ── Flagged Vehicles Summary ─────────────────────────────
    const flagged = reports.reduce((acc, r) => {
      if (!acc[r.body_number]) acc[r.body_number] = { count: 0, total_overcharge: 0 };
      acc[r.body_number].count++;
      acc[r.body_number].total_overcharge += parseFloat(r.overcharge_amount || 0);
      return acc;
    }, {});

    doc.fontSize(11).font('Helvetica-Bold').text('Vehicles with Multiple Reports:');
    doc.moveDown(0.5);
    Object.entries(flagged)
      .sort((a, b) => b[1].count - a[1].count)
      .forEach(([bodyNo, data]) => {
        doc.fontSize(10).font('Helvetica')
           .text(`  • Body No. ${bodyNo} — ${data.count} report(s), ₱${data.total_overcharge.toFixed(2)} total overcharge`);
      });

    doc.moveDown(2);

    // ── Detailed Report Entries ──────────────────────────────
    doc.fontSize(11).font('Helvetica-Bold').text('Individual Report Details:');
    doc.moveDown(0.5);

    reports.forEach((r, i) => {
      doc.fontSize(9).font('Helvetica-Bold')
         .text(`${i + 1}. Body No. ${r.body_number} — Reported ${new Date(r.reported_at).toLocaleString('en-PH')}`);
      doc.font('Helvetica')
         .text(`   Route: ${r.origin_name || 'N/A'} → ${r.destination_name || 'N/A'} (${r.distance_km || 'N/A'} km)`)
         .text(`   Legal Fare: ₱${r.calculated_fare} | Charged: ₱${r.reported_fare} | Overcharge: ₱${parseFloat(r.overcharge_amount || 0).toFixed(2)}`)
         .text(`   GPS Validated: ${r.gps_validated ? 'Yes' : 'No'} | Passenger Count: ${r.passenger_count}`);
      if (r.description) doc.text(`   Note: ${r.description}`);
      doc.moveDown(0.5);
    });

    doc.moveDown(2);
    doc.fontSize(8).font('Helvetica-Oblique')
       .text('This report was automatically generated by the TARIPA system. All data is submitted by registered commuters. GPS-validated reports are marked accordingly.',
             { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve({ filePath, fileName }));
    stream.on('error', reject);
  });
}

exports.generateAndSendWeeklyReport = async () => {
  try {
    const weekEnd   = new Date();
    const weekStart = new Date(weekEnd);
    weekStart.setDate(weekEnd.getDate() - 7);

    const weekStartStr = weekStart.toISOString().split('T')[0];
    const weekEndStr   = weekEnd.toISOString().split('T')[0];

    const [reports] = await db.query(
      `SELECT dr.*, u.email AS reporter_email
       FROM driver_reports dr
       JOIN users u ON u.id = dr.user_id
       WHERE dr.reported_at BETWEEN ? AND ?
         AND dr.status != 'dismissed'
         AND dr.included_in_ptro_report = FALSE
       ORDER BY dr.reported_at DESC`,
      [weekStartStr, weekEndStr]
    );

    if (!reports.length) {
      console.log('[PTRO] No new reports this week. Skipping email.');
      return;
    }

    const { filePath, fileName } = await generateWeeklyPDF(reports, weekStartStr, weekEndStr);

    const transporter = createTransporter();
    await transporter.sendMail({
      from:    `"TARIPA System" <${process.env.REPORT_FROM_EMAIL}>`,
      to:      process.env.PTRO_EMAIL,
      subject: `TARIPA Weekly Overcharging Report — ${weekStartStr} to ${weekEndStr}`,
      text: `Please find attached the automated TARIPA weekly overcharging report for ${weekStartStr} to ${weekEndStr}. Total reports: ${reports.length}.`,
      html: `<p>Dear PTRO,</p>
             <p>Please find attached the <strong>TARIPA weekly overcharging report</strong> for the period <strong>${weekStartStr} to ${weekEndStr}</strong>.</p>
             <p><strong>Total reports: ${reports.length}</strong></p>
             <p>This report was automatically compiled by the TARIPA system from commuter-submitted incident reports.</p>
             <br/><p>— TARIPA Automated Reporting System</p>`,
      attachments: [{ filename: fileName, path: filePath }],
    });

    // Mark reports as included
    const ids = reports.map(r => r.id);
    await db.query(
      `UPDATE driver_reports SET included_in_ptro_report = TRUE WHERE id IN (${ids.map(() => '?').join(',')})`,
      ids
    );

    // Log the PTRO report
    await db.query(
      `INSERT INTO ptro_reports (week_start, week_end, report_count, pdf_path, sent_at, sent_to, status)
       VALUES (?, ?, ?, ?, NOW(), ?, 'sent')`,
      [weekStartStr, weekEndStr, reports.length, filePath, process.env.PTRO_EMAIL]
    );

    console.log(`[PTRO] Weekly report sent. ${reports.length} reports included.`);
  } catch (err) {
    console.error('[PTRO] Failed to send report:', err.message);
    await db.query(
      "INSERT INTO ptro_reports (week_start, week_end, status) VALUES (?, ?, 'failed')",
      [new Date().toISOString().split('T')[0], new Date().toISOString().split('T')[0]]
    ).catch(() => {});
  }
};
